name: build

on:
  push:
    tags:
      - "stag-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com/ultrasoundmoney
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/ultrasoundmoney/eth-analysis
          tags: |
            type=raw,latest
            type=sha,prefix=
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=registry.digitalocean.com/ultrasoundmoney/eth-analysis:latest
          cache-to: type=inline
