name: test-build-push

on:
  push:
    tags:
      - "stag-*"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  BEACON_URL: http://***REMOVED***
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com/ultrasoundmoney
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.digitalocean.com/ultrasoundmoney/eth-analysis
          tags: |
            type=raw,latest
            type=sha,prefix=
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=registry.digitalocean.com/ultrasoundmoney/eth-analysis:latest
          cache-to: type=inline
